Update react-router to v6
diktat-static-analysis/save-cloud pull request #482
Opened 2021-12-14 08:30 UTC by petertrr

### What's done:
* Bump kotlin wrappers to pre.268
* Change API usages of react-router

2021-12-14 08:43 UTC, petertrr commented on save-frontend/src/main/kotlin/org/cqfn/save/frontend/App.kt
> +                                path = "/:owner/:name/history/execution/:executionId/details/:testSuiteName/:pluginName/:testFilePath/*"
react-router v6 has dropped support for regexes in patterns, but trailing `*` now indicates that the entire ending of path should be captured. I tested it manually and it works as expected.

2021-12-14 14:16 UTC, akuleshov7 commented
What is the need of this update?

2021-12-14 14:21 UTC, petertrr commented
> What is the need of this update?

kotlin-wrappers have updated react-router and it was blocking us from updates. And since kotlin-wrappers release only for current version of Kotlin and generally change quite fast, it's worth for us to update too

2021-12-14 15:40 UTC, kgevorkyan approved these changes
but let's also wait for @akuleshov7 for final decision, I remember, he had some doubts

2021-12-14 15:51 UTC, akuleshov7 requested changes
don't merge this week

2021-12-20 09:50 UTC, akuleshov7 approved these changes

2021-12-20 09:54 UTC, merged